# Generated by Django 2.0.3 on 2020-11-11 14:19

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogs',
            name='description',
            field=ckeditor.fields.RichTextField(),
        ),
    ]
