# Generated by Django 2.0.3 on 2020-11-11 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='portfolio_project',
            name='image',
            field=models.ImageField(upload_to='media/images/'),
        ),
    ]
